version: '3.4'

services:

  postgres-auditoria:
    container_name: msbase-postgres-auditoria-dev
    image: postgres:latest
    hostname: localhost
    ports:
        - 5432:5432
    environment:
        - POSTGRES_PASSWORD=senhaS3creta

  postgres-cadastro:
    container_name: msbase-postgres-cadastro-dev
    image: postgres:latest
    hostname: localhost
    ports:
        - 5433:5432
    environment:
        - POSTGRES_PASSWORD=senhaS3creta
  
  rabbitmq:
      container_name: msbase-rabbitmq-dev
      image: rabbitmq:3-management
      hostname: localhost
      ports:
          - 5672:5672
          - 15672:15672

  elasticsearch:
    container_name: msbase-elasticsearch-dev
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    container_name: msbase-kibana-dev
    image: docker.elastic.co/kibana/kibana:7.14.2
    ports:
      - "5601:5601"